os: windows
language: bash
before_install:
- powershell '([adsi]"WinNT://$env:COMPUTERNAME/$env:USERNAME").SetPassword($env:appveyor_rdp_password)'
install:
- choco install -y ngrok
- ngrok authtoken $NG
- ngrok tcp 3389 > /dev/null &
- while true; do echo 'LOL' && sleep 540; done
