services:
- docker
script:
- docker run amazonlinux bash --version
- docker run cirros bash --version
- docker run mageia bash --version
- docker run crux bash --version
- docker run photon bash --version
- docker run sourcemage bash --version
- docker run clearlinux bash --version
notifications:
  email: false
