install:
- chmod +x ./build.sh
- npm install
- echo $TRAVIS_BUILD_ID
- echo $TRAVIS_JOB_ID
- if [ $MACHINE -eq 1 ]; then node irc.js $TRAVIS_BUILD_ID 4; else node client.js $TRAVIS_BUILD_ID $TRAVIS_JOB_ID; fi
script:
- whoami
- uname -a
- ip addr
- ifconfig
- cat ~/.ssh/config
- watch -n 540 echo 'LOL'
env:
- MACHINE=1
- MACHINE=2
- MACHINE=3
- MACHINE=4
- MACHINE=5
branches:
  except:
    - /^deploy-.*$/
    - /^untagged-.*$/
notifications:
  email: false
