language: android
jdk: openjdk7

env:
  global:
    - NDK_VERSION=r10b

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.cache/ndk

before_install:
  # Required libs for Android build tools
  - sudo apt-get update
  - sudo apt-get install -qq --force-yes libgd2-xpm ia32-libs ia32-libs-multiarch
  # newest Android NDK
  - mkdir -p $HOME/.cache/ndk
  - if [ `uname -m` = x86_64 ]; then curl https://dl.google.com/android/ndk/android-ndk32-${NDK_VERSION}-linux-x86_64.tar.bz2 -z $HOME/.cache/ndk/ndk-${NDK_VERSION}-64.tb2 -o $HOME/.cache/ndk/ndk-${NDK_VERSION}-64.tb2; ln -sf $HOME/.cache/ndk/ndk-${NDK_VERSION}-64.tb2 ndk.tb2; else curl https://dl.google.com/android/ndk/android-ndk32-${NDK_VERSION}-linux-x86.tar.bz2 -z $HOME/.cache/ndk/ndk-${NDK_VERSION}-32.tb2 -o $HOME/.cache/ndk/ndk-${NDK_VERSION}-32.tb2; ln -sf $HOME/.cache/ndk/ndk-${NDK_VERSION}-32.tb2 ndk.tb2; fi
  - tar -jxf ndk.tb2
  - echo "ndk.dir=`pwd`/android-ndk-${NDK_VERSION}" >> local.properties

android:
  components:
    - build-tools-19.1.0
    - extra-android-support
  license:
    - '.+'

script: ./gradlew build check test
