language: python
sudo: false
python:
- "3.6"
cache: pip
before_install:
- openssl aes-256-cbc -K $encrypted_4543f1aef2eb_key -iv $encrypted_4543f1aef2eb_iv
  -in my-release-key.keystore.enc -out my-release-key.keystore -d
install:
  - pip install clint
  - pip install GitPython
  - pip install mwclient
  - pip install paramiko
  - pip install Pillow
  - pip install 'apache-libcloud >= 0.14.1'
  - pip install pyasn1
  - pip install pyasn1-modules
  - pip install PyYAML
  - pip install 'requests < 2.11'
  - pip install 'docker-py == 1.9.0'
  - git clone --depth=1 https://gitlab.com/fdroid/fdroidserver.git
  - export PATH="$PWD/fdroidserver:$PATH"
  - touch config.py
  - echo "keystorepass = \"$KEYSTORE_PASS\"" >> config.py
  - echo "keypass = \"$KEYSTORE_PASS\"" >> config.py
script:
- wget https://github.com/galeksandrp/Lightning-Browser/releases/download/deploy-7a3c7e0/app-lightningPlus-release-signed-aligned.apk
- fdroid update -c
- fdroid update
before_deploy:
- echo -e "machine github.com\nlogin galeksandrp\npassword $GITHUB_TOKEN" >> ~/.netrc
deploy:
  provider: script
  script: 'git checkout -b gh-pages && git add . && git rm -f config.py && git commit -m "Push" && git push -f origin gh-pages'
  skip_cleanup: true
  on:
    all_branches: true
notifications:
  email: false
