language: android
before_install:
- git  remote add upstream https://github.com/google/google-authenticator-android.git
- git fetch --depth=1 upstream master
- git checkout upstream/master
notifications:
  email: false
