language: cpp
addons:
  apt:
    packages:
    - nano
install:
- echo -e "machine bitbucket.org\nlogin galeksandrp\npassword $BITBUCKET_TOKEN" >> ~/.netrc
- git remote add private https://bitbucket.org/galeksandrp/zkp.git
- git fetch private
- git checkout private/master
- wget https://github.com/galeksandrp/zyxel-keenetic-packages/releases/download/v1.1/zyxel_keenetics_gpl_v.1.00_4_D0_161111.tar.bz2 -O - | tar xj --strip=1 zyxel_keenetics_gpl_v.1.00_4_D0_161111/dl
- mkdir ~/git
- mv .git ~/git
- ./configure.sh keenetic
- echo $PUBLIC_KEY >> ~/.ssh/authorized_keys
- wget https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip
- unzip ngrok-stable-linux-amd64.zip
- ./ngrok authtoken $NG
- ./ngrok tcp 22 > /dev/null &
- watch -n 540 echo 'LOL'
branches:
  except:
    - /^deploy-.*$/
notifications:
  email: false
