language: android
jdk:
  - oraclejdk8
android:
  components:
    - tools
    - tools
    - build-tools-25.0.1
    - android-25
before_install:
- openssl aes-256-cbc -K $encrypted_4543f1aef2eb_key -iv $encrypted_4543f1aef2eb_iv
  -in my-release-key.keystore.enc -out my-release-key.keystore -d
- git  remote add upstream https://github.com/google/google-authenticator-android.git
- git fetch --depth=1 upstream master
- git checkout upstream/master
- git cherry-pick $TRAVIS_COMMIT --strategy=recursive -X theirs -n || true
- echo "RELEASE_STORE_FILE=../my-release-key.keystore" > gradle.properties
- echo "RELEASE_STORE_PASSWORD=$KEYSTORE_PASS" >> gradle.properties
- echo "RELEASE_KEY_ALIAS=alias_name" >> gradle.properties
- echo "RELEASE_KEY_PASSWORD=$KEYSTORE_PASS" >> gradle.properties
before_deploy:
  - echo -e "machine github.com\nlogin galeksandrp\npassword $GITHUB_TOKEN" >> ~/.netrc
  - echo $TRAVIS_COMMIT > .git/HEAD
  - git tag -f v$(grep versionName app/build.gradle | cut -d '"' -f 2)-$TRAVIS_BRANCH-deploy
  - git push origin -f v$(grep versionName app/build.gradle | cut -d '"' -f 2)-$TRAVIS_BRANCH-deploy
deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  skip_cleanup: true
  file: 
  - AuthenticatorApp/build/outputs/apk/*.apk
  file_glob: true
  overwrite: true
  on:
    all_branches: true
branches:
  except:
    - /^deploy-.*$/
    - /^.*-deploy$/
    - /^untagged-.*$/
script:
- ./gradlew build -x lint
notifications:
  email: false
