language: android
jdk:
  - oraclejdk8
before_install:
- git remote add upstream https://gitlab.com/fdroid/fdroidclient.git
- git fetch --depth=1 upstream master
- git checkout upstream/master
notifications:
  email: false
