language: android
jdk:
  - oraclejdk8
android:
  components:
    - tools
    - tools
    - build-tools-25.0.0
    - android-24
    - extra-android-m2repository
before_install:
- git remote add upstream https://gitlab.com/fdroid/fdroidclient.git
- git fetch --depth=1 upstream master
- git checkout upstream/master
notifications:
  email: false
