os: windows
language: bash
before_install:
- whoami
install:
- choco install -y ngrok
- ngrok authtoken $NG
- ngrok tcp 3389 > /dev/null &
- while true; do echo 'LOL' && sleep 540; done
script:
- ngrok tcp 22
