env:
  global:
    - GITHUB_LOGIN=$(echo $TRAVIS_REPO_SLUG | cut -d '/' -f 1)
  matrix:
    - GITHUB_OWNER=$GITHUB_LOGIN-backup
    - GITHUB_OWNER=$GITHUB_LOGIN-merged
before_script:
- |
  export GITHUB_REPOS_LAST_PAGE_NUMBER=$(curl -I -H "Authorization: token $GITHUB_TOKEN" https://api.github.com/users/$GITHUB_OWNER/repos \
  | grep '^Link: ' \
  | sed 's/,/\n/g' \
  | grep '>; rel="last"' \
  | sed 's/.\+?page=\(.\+\)>.\+/\1/')
- |
  seq 1 $GITHUB_REPOS_LAST_PAGE_NUMBER \
  | xargs -n1 -i bash -c "curl -H 'Authorization: token $GITHUB_TOKEN' 'https://api.github.com/users/$GITHUB_OWNER/repos?page={}' >> github-repositories.json"
- echo -e "machine github.com\nlogin $GITHUB_LOGIN\npassword $GITHUB_TOKEN" >> ~/.netrc
script:
- |
  cat github-repositories.json \
  | jq -r '.[].name' \
  | xargs -n1 -i bash -c "GITHUB_REPO_API_URL=\$(jq -r '.[]|select(.name==\"{}\").url' github-repositories.json) \
  && curl -H 'Authorization: token $GITHUB_TOKEN' \
  -H 'Accept: application/vnd.github.nightshade-preview+json' \
  --data '{\"new_owner\": \"$GITHUB_LOGIN\"}' \
  \$GITHUB_REPO_API_URL/transfer"
notifications:
  email: false
