language: python
python:
- "3.6"
install:
- pip install fdroidserver
script:
- mkdir repo
- wget https://github.com/galeksandrp/Lightning-Browser/releases/download/deploy-7a3c7e0/app-lightningPlus-release-signed-aligned.apk
- cd ..
- fdroid update -c
- fdroid update
notifications:
  email: false
