language: android
jdk:
  - oraclejdk7
before_install:
- git remote add upstream https://github.com/bpellin/keepassdroid.git
- git fetch --depth=1 upstream master
- git checkout upstream/master
notifications:
  email: false
