before_install:
  - echo -e "machine bitbucket.org\nlogin galeksandrp\npassword $BITBUCKET_TOKEN" >> ~/.netrc
install:
- git remote add private https://bitbucket.org/galeksandrp/xml.git
- git fetch --depth=1 private master
- git checkout private/master
script:
- xmllint --xpath '//FixedDownloadUrl/text()' xml.xml | sed 's/http/\nhttp/g' | xargs -n1 -i bash -c 'RESP=$(curl -f -s -I {}) || echo $RESP | grep Location || echo {}'
notifications:
  email: false
