language: cpp
script: |-
    curl -X POST 'https://ci.appveyor.com/api/builds' -H "Authorization: Bearer $APPVEYOR_TOKEN" -H 'Content-Type: application/json' -d '{"accountName": "galeksandrp", "projectSlug": "au-packages", "branch": "1c"}'
    curl -X POST 'https://ci.appveyor.com/api/builds' -H "Authorization: Bearer $APPVEYOR_TOKEN" -H 'Content-Type: application/json' -d '{"accountName": "galeksandrp", "projectSlug": "au-packages", "branch": "master"}'
notifications:
  email: false
