language: android
jdk:
  - oraclejdk8
android:
  components:
    - build-tools-25.0.1
    - android-25
before_install:
- git  remote add upstream https://github.com/google/google-authenticator-android.git
- git fetch --depth=1 upstream master
- git checkout upstream/master
notifications:
  email: false
