env:
  global:
    - GITHUB_LOGIN=$(echo $TRAVIS_REPO_SLUG | cut -d '/' -f 1)
  matrix:
    - GITHUB_OWNER=$GITHUB_LOGIN-backup
    - GITHUB_OWNER=$GITHUB_LOGIN-merged
    - GITHUB_OWNER=$GITHUB_LOGIN-ci
before_script:
- |
  export GITHUB_REPOS_LAST_PAGE_NUMBER=$(curl -I -H "Authorization: token $GITHUB_TOKEN" https://api.github.com/users/$GITHUB_OWNER/repos \
  | grep '^Link: ' \
  | sed 's/,/\n/g' \
  | grep '>; rel="last"' \
  | sed 's/.\+?page=\(.\+\)>.\+/\1/')
- |
  seq 1 $GITHUB_REPOS_LAST_PAGE_NUMBER \
  | xargs -n1 -i bash -c "curl -H 'Authorization: token $GITHUB_TOKEN' 'https://api.github.com/users/$GITHUB_OWNER/repos?page={}' >> github-repositories.json"
- echo -e "machine github.com\nlogin $GITHUB_LOGIN\npassword $GITHUB_TOKEN" >> ~/.netrc
script:
- |
  cat github-repositories.json \
  | jq -r '.[]|select(.fork)|.name' \
  | xargs -n1 -i bash -c "GITHUB_REPO_API_URL=\$(jq -r '.[]|select(.name==\"{}\").url' github-repositories.json) \
  GITHUB_REPO_UPSTREAM_URL=\$(curl -H 'Authorization: token $GITHUB_TOKEN' \$GITHUB_REPO_API_URL \
  | jq -r '.parent.clone_url') \
  GITHUB_REPO_URL=\$(jq -r '.[]|select(.name==\"{}\").clone_url' github-repositories.json) \
  GITHUB_REPO_DEFAULT_BRANCH=\$(jq -r '.[]|select(.name==\"{}\").default_branch' github-repositories.json) \
  && git clone \$GITHUB_REPO_UPSTREAM_URL \
  && cd {} \
  && cp -Rf .git/refs/remotes/origin/* .git/refs/heads/ \
  && rm -f .git/refs/heads/HEAD \
  && cat .git/packed-refs \
  | grep ' refs/remotes/origin/' \
  | grep -v \" refs/remotes/origin/\$GITHUB_REPO_DEFAULT_BRANCH$\" \
  | sed 's& refs/remotes/origin/& refs/heads/&' >> .git/packed-refs \
  && git remote add fork \$GITHUB_REPO_URL \
  && git push fork --all \
  && git push fork --tags \
  ; cd .. \
  && rm -rf {}"
notifications:
  email: false
