language: python
python:
- "3.6"
cache: pip
install:
  - pip install clint
  - pip install GitPython
  - pip install mwclient
  - pip install paramiko
  - pip install Pillow
  - pip install 'apache-libcloud >= 0.14.1'
  - pip install pyasn1
  - pip install pyasn1-modules
  - pip install PyYAML
  - pip install 'requests < 2.11'
  - pip install 'docker-py == 1.9.0'
  - git clone --depth=1 https://gitlab.com/fdroid/fdroidserver.git
  - export PATH="$PWD/fdroidserver:$PATH"
  - touch config.py
script:
- wget https://github.com/galeksandrp/Lightning-Browser/releases/download/deploy-7a3c7e0/app-lightningPlus-release-signed-aligned.apk
- fdroid update -c
- fdroid update
notifications:
  email: false
