language: android
jdk: oraclejdk8
sudo: true  # For the 7.5GB limit

env:
  global:
    - NDK_VERSION=r11c
    # Coverity
    - secure: "DTBBKdwZE5yxPjJQG8/wU/+LJ1A3MtUYNaf8O/yhmQNo4UcxQF+3KOoY5OK4vvoTewisUqnVRhXhD8rMYzBZiNtaGF8eSMGXVWUVb6YhOPQ0oMHKSmVgopEHzhoGa+9HDJ6xyQZdALJB8GVlwamTwO/1qk/xI02mjUNEtdk8cuc="

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/dists/
    - $HOME/.cache/ci-support
    - $HOME/.cache/lint
    - $HOME/.cache/ndk
before_cache:
  - find $HOME/.gradle -name "*.lock" -exec rm {} \;
  - rm -rf $HOME/.gradle/caches/[1-9]*

addons:
  apt:
    packages:
      - xqilla # ./scripts/check-lint-count.bash
  coverity_scan:
    project:
      name: "connectbot/connectbot"
      description: "The first SSH client for Android."
    notification_email: developers@connectbot.org
    build_command_prepend: "./gradlew clean"
    build_command: "./gradlew assemble"
    branch_pattern: coverity_scan

before_script:
  # Create and start emulator as early as possible
  - echo no | android create avd --force -n test -t android-23 --abi default/armeabi-v7a -s "768x1280" --device "Nexus 4" -c 128M
  - emulator -avd test -no-audio -no-window &
  # Download the emulator support stuff
  - mkdir -p $HOME/.cache/ci-support
  - curl -L https://github.com/connectbot/ci-support/archive/master.zip -z $HOME/.cache/ci-support/master.zip -o $HOME/.cache/ci-support/master.zip
  - unzip -q $HOME/.cache/ci-support/master.zip -d $HOME
  # newest Android NDK
  - mkdir -p $HOME/.cache/ndk
  - curl https://dl.google.com/android/repository/android-ndk-${NDK_VERSION}-linux-x86_64.zip -z $HOME/.cache/ndk/ndk-${NDK_VERSION}.zip -o $HOME/.cache/ndk/ndk-${NDK_VERSION}.zip
  - unzip -q $HOME/.cache/ndk/ndk-$NDK_VERSION.zip -d $HOME
  - echo "ndk.dir=$HOME/android-ndk-$NDK_VERSION" >> local.properties
  # For the lint checking mechanism
  - mkdir -p $HOME/.cache/lint
  ### The rest of the commands need the emulator running
  - android-wait-for-emulator
  - adb shell input keyevent 82 &
  # Install our ci-support stuff to make the emulator tests more reliable.
  - adb install -r $HOME/ci-support-master/apk/android_emulator_hacks.apk
  - adb shell pm grant no.finn.android_emulator_hacks android.permission.SET_ANIMATION_SCALE
  - adb shell am start -n no.finn.android_emulator_hacks/no.finn.android_emulator_hacks.HackActivity

android:
  components:
    - platform-tools
    - tools
    - build-tools-23.0.3
    - android-23
    - sys-img-armeabi-v7a-android-23
    - extra-android-support
    - extra-android-m2repository
  license:
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'

script:
  # Split up to reduce memory requirements
  - ./gradlew --stacktrace clean
  - ./gradlew --stacktrace assemble
  - ./gradlew --stacktrace check
  - ./gradlew --stacktrace jacocoUnitTestDebugReport
  - ./gradlew --stacktrace jacocoCombinedReport
  - ./scripts/check-lint-count.bash app/build/outputs/lint-results-debug.xml $HOME/.cache/lint/lint-results.xml

after_success: ./gradlew coveralls
