env:
- GITHUB_LOGIN=$(echo $TRAVIS_REPO_SLUG | cut -d '/' -f 1)
before_script:
- |
  export GITHUB_REPOS_LAST_PAGE_NUMBER=$(curl -I -H "Authorization: token $GITHUB_TOKEN" https://api.github.com/user/repos?affiliation=owner \
  | grep '^Link: ' \
  | sed 's/,/\n/g' \
  | grep '>; rel="last"' \
  | grep -o '[0-9]')
- echo -e "machine github.com\nlogin $GITHUB_LOGIN\npassword $GITHUB_TOKEN" >> ~/.netrc
script:
- |
  seq 1 $GITHUB_REPOS_LAST_PAGE_NUMBER \
  | xargs -n1 -i bash -c "curl -H 'Authorization: token $GITHUB_TOKEN' 'https://api.github.com/user/repos?affiliation=owner&page={}' > github-repositories-{}.json \
  && . functions.sh \
  && githubReposPage github-repositories-{}.json"
notifications:
  email: false
