language: android
before_install:
- git remote add upstream https://github.com/miracle2k/android-autostarts.git
- git fetch --depth=1 upstream master
- git checkout upstream/master
- pip install --user fabric
- pip install --user py-androidbuild
- pip install --user android2po
- pip install --user termcolor
- echo "sdk_dir = $ANDROID_HOME" > .fabricrc
- echo "deploy_host = travis@localhost$TRAVIS_BUILD_DIR" >> .fabricrc
- echo "deploy_dir = $TRAVIS_BUILD_DIR" >> .fabricrc
script:
- fab build
notifications:
  email: false
