language: android
sudo: false
dist: trusty
addons:
  apt:
    packages:
      - python3
      - python3-pip
      - oracle-java8-installer
cache: pip
before_install:
- openssl aes-256-cbc -K $encrypted_4543f1aef2eb_key -iv $encrypted_4543f1aef2eb_iv
  -in my-release-key.keystore.enc -out my-release-key.keystore -d
install:
  - pip3 install --user clint
  - pip3 install --user GitPython
  - pip3 install --user mwclient
  - pip3 install --user paramiko
  - pip3 install --user Pillow
  - pip3 install --user 'apache-libcloud >= 0.14.1'
  - pip3 install --user pyasn1
  - pip3 install --user pyasn1-modules
  - pip3 install --user PyYAML
  - pip3 install --user 'requests < 2.11'
  - pip3 install --user 'docker-py == 1.9.0'
  - git clone --depth=1 https://gitlab.com/fdroid/fdroidserver.git
  - export PATH="$PWD/fdroidserver:$PATH"
  - touch config.py
  - echo "keystorepass = \"$KEYSTORE_PASS\"" >> config.py
  - echo "keypass = \"$KEYSTORE_PASS\"" >> config.py
script:
- mkdir repo
- cd repo
- wget https://github.com/galeksandrp/Lightning-Browser/releases/download/deploy-7a3c7e0/app-lightningPlus-release-signed-aligned.apk
- cd ..
- fdroid update -c
- fdroid update
before_deploy:
- echo -e "machine github.com\nlogin galeksandrp\npassword $GITHUB_TOKEN" >> ~/.netrc
deploy:
  provider: script
  script: 'git checkout -b gh-pages && git add repo && git commit -m "Push" && git push -f origin gh-pages'
  skip_cleanup: true
  on:
    all_branches: true
notifications:
  email: false
