language: node_js
node_js:
  - "6"
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
install:
- npm install -g dredd
- npm install
script:
- node app.js &
- dredd apiary.apib http://127.0.0.1:3000 -r apiary -j apiaryApiKey:$APIARY_API_KEY -j apiaryApiName:test11603
notifications:
  email: false
