language: cpp
install:
- git remote add private https://github.com/samyk/pwnat.git
- git fetch private
- git checkout private/master
script:
- make -j3
before_deploy:
  - export COMMIT=$(git describe --abbrev=40 --always)
  - export SHORT_COMMIT=$(git describe --always)
  - tar cfz ~/pwnat-$SHORT_COMMIT.tar.gz .
  - echo version > $COMMIT
  - echo -e "machine github.com\nlogin galeksandrp\npassword $GITHUB_TOKEN" >> ~/.netrc
  - git tag deploy-pwnat-$SHORT_COMMIT $TRAVIS_COMMIT || true
  - git push origin deploy-pwnat-$SHORT_COMMIT -f
  - echo $TRAVIS_COMMIT > .git/HEAD
deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  skip_cleanup: true
  file: 
  - $COMMIT
  - $HOME/pwnat-$SHORT_COMMIT.tar.gz
  overwrite: true
  on:
    all_branches: true
branches:
  except:
    - /^deploy-.*$/
    - /^untagged-.*$/
notifications:
  email: false
