addons:
  apt:
    packages:
    - cvs
install:
- cvs --version
script:
- rsync -av rsync://$GITHUB_REPO.cvs.sourceforge.net/cvsroot/$GITHUB_REPO/\* $GITHUB_REPO
- touch ~/.subversion/servers
- echo 'store-plaintext-passwords = no' >> ~/.subversion/servers
- svn co --username=guest --password="" http://cvs2svn.tigris.org/svn/cvs2svn/trunk cvs2svn-trunk
- mkdir cvs2git-tmp
- cvs2svn-trunk/cvs2git --blobfile=cvs2git-tmp/git-blob.dat --dumpfile=cvs2git-tmp/git-dump.dat --username=cvs2git $GITHUB_REPO/$GITHUB_REPO
- git init --bare $GITHUB_REPO.git
- cd $GITHUB_REPO.git
- git fast-import --export-marks=../cvs2git-tmp/git-marks.dat <../cvs2git-tmp/git-blob.dat
- git fast-import --import-marks=../cvs2git-tmp/git-marks.dat <../cvs2git-tmp/git-dump.dat
- git remote add https://github.com/$GITHUB_NAME/$GITHUB_REPO.git
- echo -e "machine github.com\nlogin $GITHUB_NAME\npassword $GITHUB_TOKEN" >> ~/.netrc
- git push --all
- git push --tags
branches:
  except:
    - /^deploy-.*$/
notifications:
  email: false
env:
  global:
  - GITHUB_NAME=$(echo $TRAVIS_REPO_SLUG | cut -d '/' -f 1)
  matrix:
  - GITHUB_REPO=abills
