script:
  - git fetch origin
  - git branch -r | grep '^ *origin/docker-arch' | cut -d '/' -f2 | xargs -i bash -c "curl -d '{\"source_name\":\"{}\"}' \"$DOCKER_HUB_BUILD_TRIGGER_URL\""
notifications:
  email: false
