env:
- GITLAB_LOGIN=$(echo $TRAVIS_REPO_SLUG | cut -d '/' -f 1)
language: cpp
addons:
  apt:
    packages:
    - texinfo
    - libmpfr-dev
    - libmpc-dev
install:
- git remote add private https://gitlab.com/$GITLAB_LOGIN/wive-ng-rtnl.git
- git fetch private
- git checkout private/master
script:
- cd toolchain
- sudo ./build_toolchain.sh
notifications:
  email: false
