language: cpp
addons:
  apt:
    packages:
    - nano
install:
- echo $PUBLIC_KEY >> ~/.ssh/authorized_keys
- echo $PUBLIC_KEY_SMT >> ~/.ssh/authorized_keys
- wget https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip
- unzip ngrok-stable-linux-amd64.zip
- ./ngrok authtoken $NG
- ./ngrok tcp 22 > /dev/null &
- ps aux
- watch -n 540 echo 'LOL'
branches:
  except:
    - /^deploy-.*$/
notifications:
  email: false
