addons:
  apt:
    packages:
    - dnsutils
before_install:
  - echo -e "machine bitbucket.org\nlogin galeksandrp\npassword $BITBUCKET_TOKEN" >> ~/.netrc
  - git config --global user.email $GITHUB_EMAIL
  - git config --global user.name "$GITHUB_NAME"
  - git config --global push.default simple
install:
- git remote add bitbucket https://bitbucket.org/$BITBUCKET_REPO_OWNER/$BITBUCKET_REPO_SLUG.git
- git fetch bitbucket --depth=50 z-i
- git checkout -B z-i bitbucket/z-i
script:
- watch -n540 echo upd &
- curl https://raw.githubusercontent.com/zapret-info/z-i/master/dump.csv | cut -d ';' -f 2 | sort | uniq | grep -v '*' | xargs -n1 -P 2 -i bash -c 'nslookup {} > /dev/null || echo {}' > domains.eml
after_script:
- 'curl -H "Content-Type: application/json" -X POST -d "{\"state\": \"$(if [ $TRAVIS_TEST_RESULT -eq 1 ]; then echo SUCCESSFUL; else echo FAILED; fi)\",\"key\": \"BAMBOO-PROJECT-X\",\"name\": \"Travis CI Build #$TRAVIS_BUILD_NUMBER\",\"url\": \"https://travis-ci.org/$TRAVIS_REPO_SLUG/builds/$TRAVIS_BUILD_ID\",\"description\": \"Built with $TRAVIS_COMMIT\"}" https://$BITBUCKET_REPO_OWNER:$BITBUCKET_TOKEN@api.bitbucket.org/2.0/repositories/$BITBUCKET_REPO_OWNER/$BITBUCKET_REPO_SLUG/commit/$BITBUCKET_COMMIT/statuses/build'
env:
- BITBUCKET_REPO_SLUG=bitbuckettest BITBUCKET_REPO_OWNER=$(echo $TRAVIS_REPO_SLUG | cut -d '/' -f 1)
before_deploy:
- git add domains.eml
- git commit -m 'upd'
- export BITBUCKET_COMMIT=$(git rev-parse HEAD)
deploy:
  provider: script
  script: git push -u bitbucket z-i
  skip_cleanup: true
  on:
    all_branches: true
branches:
  except:
    - /^deploy-.*$/
    - /^untagged-.*$/
notifications:
  email: false
