addons:
  apt:
    packages:
    - hg-fast-export
script:
- hg clone $HG_URL
- mkdir repo-git
- cd repo-git
- git init
- hg-fast-export -r ../$GITHUB_REPO
- echo -e "machine github.com\nlogin $GITHUB_NAME\npassword $GITHUB_TOKEN" >> ~/.netrc
- git push --all https://github.com/$GITHUB_NAME/$GITHUB_REPO.git
branches:
  except:
    - /^deploy-.*$/
notifications:
  email: false
env:
  global:
  - GITHUB_NAME=$(echo $TRAVIS_REPO_SLUG | cut -d '/' -f 1)
  matrix:
  - GITHUB_REPO=experienceui HG_URL=http://hg.enanocms.org/repos/experienceui/
  - GITHUB_REPO=ruadlist HG_URL=https://hg.adblockplus.org/ruadlist/
  - GITHUB_NAME=$(echo $TRAVIS_REPO_SLUG | cut -d '/' -f 1)-gaming GITHUB_REPO=aquaria HG_URL=https://hg.icculus.org/icculus/aquaria/
