script:
- hg clone $HG_URL
- cd $BITBUCKET_REPO
- echo -e "machine bitbucket.org\nlogin $GITHUB_NAME\npassword $BITBUCKET_TOKEN" >> ~/.netrc
- hg push https://bitbucket.org/$GITHUB_NAME/$BITBUCKET_REPO
branches:
  except:
    - /^deploy-.*$/
notifications:
  email: false
env:
  global:
  - GITHUB_NAME=$(echo $TRAVIS_REPO_SLUG | cut -d '/' -f 1)
  matrix:
  - BITBUCKET_REPO=experienceui HG_URL=http://hg.enanocms.org/repos/experienceui/
  - BITBUCKET_REPO=ruadlist HG_URL=https://hg.adblockplus.org/ruadlist/
