sudo: true
env:
  global:
    - NDK_VERSION=r10e
language: android
jdk:
  - oraclejdk8
android:
  components:
  - tools
  - tools
  - build-tools-23.0.3
  - build-tools-24.0.3
  - extra-android-m2repository
  - platform-tools
  - android-23
  - android-25
  - extra-android-support
addons:
  apt:
    sources:
    - git-core
    packages:
    - git
before_install:
- openssl aes-256-cbc -K $encrypted_4543f1aef2eb_key -iv $encrypted_4543f1aef2eb_iv
  -in my-release-key.keystore.enc -out my-release-key.keystore -d
- git remote add upstream https://github.com/AdAway/AdAway.git
- git fetch --depth=1 upstream --tags -q
- git checkout $(git tag --sort=-v:refname -l 'v*' | head -1)
- git cherry-pick $TRAVIS_COMMIT --strategy=recursive -X theirs -n || true
- mkdir -p ~/.gradle
- echo "signingStoreLocation=$TRAVIS_BUILD_DIR/my-release-key.keystore" > ~/.gradle/gradle.properties
- echo "signingStorePassword=$KEYSTORE_PASS" >> ~/.gradle/gradle.properties
- echo "signingKeyAlias=alias_name" >> ~/.gradle/gradle.properties
- echo "signingKeyPassword=$KEYSTORE_PASS" >> ~/.gradle/gradle.properties
before_deploy:
  - echo -e "machine github.com\nlogin galeksandrp\npassword $GITHUB_TOKEN" >> ~/.netrc
  - echo $TRAVIS_COMMIT > .git/HEAD
  - git tag -f deploy-$TRAVIS_BRANCH
  - git push origin -f deploy-$TRAVIS_BRANCH
deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  skip_cleanup: true
  file: 
  - AdAway/build/outputs/apk/*.apk
  file_glob: true
  overwrite: true
  on:
    all_branches: true
install:
- wget https://dl.google.com/android/ndk/android-ndk-$NDK_VERSION-linux-x86_64.bin
- chmod +x android-ndk-$NDK_VERSION-linux-x86_64.bin
- ./android-ndk-$NDK_VERSION-linux-x86_64.bin | egrep -v ^Extracting
- export ANDROID_NDK_HOME=`pwd`/android-ndk-$NDK_VERSION
- export PATH=${PATH}:${ANDROID_NDK_HOME}:/usr/local/android-sdk/build-tools/23.0.1
script:
- cd AdAway
- ndk-build
- cd $TRAVIS_BUILD_DIR
- ./gradlew renameExecutables
- ./gradlew build
branches:
  except:
    - /^deploy-.*$/
    - /^untagged-.*$/
notifications:
  email: false
