version: 1.0.{build}
branches:
  only:
  - /^appveyor-.*$/
init:
- ps: '#$blockRdp = $true; iex ((new-object net.webclient).DownloadString(''https://gist.githubusercontent.com/galeksandrp/d3ccaec044abed5d0ba2a01e72ad4c8b/raw/8abed8b5af35cb879abbb0e2ba4de21b5f097c08/enable-rdp.ps1''))'
clone_script:
- cmd: >-
    appveyor DownloadFile https://curl.haxx.se/download/curl-7.50.3.zip

    cd ..

    7z x %APPVEYOR_BUILD_FOLDER%\curl-7.50.3.zip

    rd /s /q %APPVEYOR_BUILD_FOLDER%

    ren curl-7.50.3 %APPVEYOR_PROJECT_NAME%

    cd %APPVEYOR_BUILD_FOLDER%
environment:
  RDP_PASSWORD:
    secure: EPntnepDJxCOkdpUUnJiYQ==
install:
- cmd: >-
    set MSYSTEM=MINGW32

    C:\MinGW\bin\mingw-get update

    C:\MinGW\bin\mingw-get upgrade
build_script:
- cmd: >-
    echo %APPVEYOR_BUILD_FOLDER% | sed "s&\\\\&/&g" > output.txt

    set /p APPVEYOR_BUILD_DIRECTORY=<output.txt

    C:\MinGW\msys\1.0\bin\bash -l -c "cd $APPVEYOR_BUILD_DIRECTORY && mingw32-make mingw32"
artifacts:
- path: config.log