version: 1.0.{build}
branches:
  only:
  - /^appveyor-.*$/
image: Visual Studio 2017
init:
- cmd: >-
    echo machine github.com >> %USERPROFILE%\_netrc

    echo login %GITHUB_NAME% >> %USERPROFILE%\_netrc

    echo password %GITHUB_TOKEN% >> %USERPROFILE%\_netrc

    echo machine bitbucket.org >> %USERPROFILE%\_netrc

    echo login galeksandrp >> %USERPROFILE%\_netrc

    echo password %BITBUCKET_TOKEN% >> %USERPROFILE%\_netrc
    
    git config --global user.name "%GIT_NAME%"
    
    git config --global user.email %GIT_EMAIL%
clone_script:
- ps: '$blockRdp = $true; iex ((new-object net.webclient).DownloadString(''https://gist.githubusercontent.com/galeksandrp/d3ccaec044abed5d0ba2a01e72ad4c8b/raw/8abed8b5af35cb879abbb0e2ba4de21b5f097c08/enable-rdp.ps1''))'
