version: 1.0.{build}
branches:
  only:
  - /^appveyor-.*$/
clone_script:
- cmd: git clone -q --depth=1 https://github.com/klaxa/mkvserver_mk2.git %APPVEYOR_BUILD_FOLDER%
install:
- cmd: >-
    set MSYSTEM=MINGW64

    set CHERE_INVOKING=enabled_from_arguments

    C:\msys64\usr\bin\bash --login -c "pacman -Syu --noconfirm"

    C:\msys64\usr\bin\bash --login -c "pacman -S --noconfirm mingw-w64-x86_64-ffmpeg"
build_script:
- cmd: >-
    C:\msys64\usr\bin\bash --login -c "make"
artifacts:
- path: server*
