version: 1.0.{build}
branches:
  only:
  - /^appveyor-.*$/
configuration: Release
init:
- ps: '#$blockRdp = $true; iex ((new-object net.webclient).DownloadString(''https://gist.githubusercontent.com/galeksandrp/d3ccaec044abed5d0ba2a01e72ad4c8b/raw/8abed8b5af35cb879abbb0e2ba4de21b5f097c08/enable-rdp.ps1''))'
clone_script:
- cmd: git clone --depth=1 https://github.com/ldo/dvdauthor.git %APPVEYOR_BUILD_FOLDER%
environment:
  RDP_PASSWORD:
    secure: EPntnepDJxCOkdpUUnJiYQ==
build_script:
- cmd: >-
    set MSYSTEM=MINGW64

    set CHERE_INVOKING=enabled_from_arguments

    C:\msys64\usr\bin\bash --login -c "pacman -S --noconfirm mingw-w64-x86_64-{libxml2,libpng,freetype,libdvdread}"
    
    appveyor DownloadFile "https://ci.appveyor.com/api/buildjobs/y64e20327bctgqeu/artifacts/artifacts/mingw-w64-x86_64-docbook2x-0.8.6-1-any.pkg.tar.xz"
    
    C:\msys64\usr\bin\bash --login -c "pacman -U --noconfirm mingw-w64-x86_64-docbook2x-0.8.6-1-any.pkg.tar.xz"

    C:\msys64\usr\bin\bash --login -c "./bootstrap"

    C:\msys64\usr\bin\bash --login -c "./configure --prefix=/mingw64"

    C:\msys64\usr\bin\bash --login -c "ls -la"

    C:\msys64\usr\bin\bash --login -c "make -j3"
    
    C:\msys64\usr\bin\bash --login -c "make DESTDIR=mingw64 install"
artifacts:
- path: mingw64
