version: 1.0.{build}
branches:
  only:
  - /^appveyor-.*$/
clone_script:
- cmd: git clone -q --depth=1 https://github.com/z3APA3A/3proxy.git %APPVEYOR_BUILD_FOLDER%
install:
- cmd: >-
    set MSYSTEM=MINGW64

    set CHERE_INVOKING=enabled_from_arguments
build_script:
- cmd: >-
    echo %MSYSTEM%

    echo %CHERE_INVOKING%

    C:\msys64\usr\bin\bash --login -c "make -j3 -f Makefile.win"
    
    C:\msys64\usr\bin\bash --login -c "make sed 's&$(INSTALL_BIN) -s $(INSTALL_OBJS) $(BINDIR)&$(INSTALL_BIN) -s bin/* $(BINDIR)&' -i Makefile.Linux"
    
    C:\msys64\usr\bin\bash --login -c "make DESTDIR=mingw64 prefix=mingw64 install -f Makefile.Linux"
artifacts:
- path: mingw64
