version: 1.0.{build}
branches:
  only:
  - /^appveyor-.*$/
clone_script:
- cmd: git clone -q --depth=1 https://github.com/jech/polipo.git %APPVEYOR_BUILD_FOLDER%
install:
- cmd: >-
    set MSYSTEM=MINGW64

    set CHERE_INVOKING=enabled_from_arguments
build_script:
- cmd: >-
    echo %MSYSTEM%

    echo %CHERE_INVOKING%

    C:\msys64\usr\bin\bash --login -c 'mingw32-make -j3 EXE=.exe LDLIBS=-lwsock32'
artifacts:
- path: polipo.exe