version: 1.0.{build}
branches:
  only:
  - /^appveyor-.*$/
init:
- ps: '#$blockRdp = $true; iex ((new-object net.webclient).DownloadString(''https://gist.githubusercontent.com/galeksandrp/d3ccaec044abed5d0ba2a01e72ad4c8b/raw/8abed8b5af35cb879abbb0e2ba4de21b5f097c08/enable-rdp.ps1''))'
clone_script:
- cmd: git clone -q --depth=1 https://git.videolan.org/git/x264.git %APPVEYOR_BUILD_FOLDER%
environment:
  RDP_PASSWORD:
    secure: EPntnepDJxCOkdpUUnJiYQ==
install:
- cmd: >-
    set MSYSTEM=MINGW64

    set CHERE_INVOKING=enabled_from_arguments

    C:\msys64\usr\bin\bash --login -c "pacman -S --noconfirm mingw-w64-x86_64-yasm"
build_script:
- cmd: >-
    C:\msys64\usr\bin\bash --login -c "./configure --prefix=mingw64"

    C:\msys64\usr\bin\bash --login -c "make -j3"
    
    C:\msys64\usr\bin\bash --login -c "make DESTDIR=mingw64 install"
artifacts:
- path: mingw64
