version: 1.0.{build}
branches:
  only:
  - /^appveyor-.*$/
init:
- cmd: >-
    echo machine github.com >> %USERPROFILE%\_netrc

    echo login %GITHUB_NAME% >> %USERPROFILE%\_netrc

    echo password %GITHUB_TOKEN% >> %USERPROFILE%\_netrc

    echo machine bitbucket.org >> %USERPROFILE%\_netrc

    echo login galeksandrp >> %USERPROFILE%\_netrc

    echo password %BITBUCKET_TOKEN% >> %USERPROFILE%\_netrc
    
    git config --global user.name "%GIT_NAME%"
    
    git config --global user.email %GIT_EMAIL%
clone_script:
- ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
- ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
