version: 1.0.{build}
environment:
  CLIENT_OVPN_SECRET:
    secure: irgtLRwTfMXByjgzmUN3toxIv1xhiXGXhmE8sVQ/PKw=
  OPENVPN_PASSWORD:
    secure: U4aH2bodfl5Tcb3+1sm3cubPd9sfzjDfcQUfTOhP7Lk=
  DOMAIN_PASSWORD:
    secure: nbq6iPPffGciS+7eCuyKHjJigAK1uMa0wh5bV3TdGwo=
  DOMAIN_LOGIN:
    secure: Q4A9DZowXnvD+w+/hbby5A==
  DOMAIN:
    secure: kps54NW2JZKCecVSOKvF1A==
init:
- ps: if ($env:APPVEYOR_REPO_COMMIT_MESSAGE -match '[ci rdp] ') {iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))}
install:
- ps: >-
    iex ((New-Object Net.WebClient).DownloadString('https://raw.githubusercontent.com/appveyor/secure-file/master/install.ps1'))

    Disable-NetFirewallRule -DisplayName 'Core Networking - Dynamic Host Configuration Protocol (DHCP-Out)'
- cmd: >-
    choco install -y -i openvpn

    appveyor-tools\secure-file -decrypt client.ovpn.enc -secret %CLIENT_OVPN_SECRET% -out "%PROGRAMFILES%\OpenVPN\config\client.ovpn"

    cd "%PROGRAMFILES%\OpenVPN\config"

    echo appveyor>> auth.txt

    echo %OPENVPN_PASSWORD%>> auth.txt
- ps: >-
    echo "echo>$env:TMP\client.ovpn.lock || true" | out-file "$env:PROGRAMFILES\OpenVPN\config\client_up.bat" -encoding UTF8

    start "$env:PROGRAMFILES\OpenVPN\bin\openvpn-gui" -argumentlist '--connect','client.ovpn'

    while(!(Test-Path $env:TMP\client.ovpn.lock)) {
        Start-Sleep -Seconds 1
    }
build_script:
- ps: >-
    $password = ConvertTo-SecureString "$env:DOMAIN_PASSWORD" -AsPlainText -Force

    $credential = New-Object System.Management.Automation.PSCredential -ArgumentList "$env:DOMAIN_LOGIN", $password

    Add-Computer -domainname "$env:DOMAIN" -credential $credential
    
    Restart-Computer
on_finish:
- ps: if ($env:APPVEYOR_REPO_COMMIT_MESSAGE -match '[ci rdp] ') {$blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))}
