version: 1.0.{build}
branches:
  only:
  - /^appveyor-.*$/
init:
- ps: '#$blockRdp = $true; iex ((new-object net.webclient).DownloadString(''https://gist.githubusercontent.com/galeksandrp/d3ccaec044abed5d0ba2a01e72ad4c8b/raw/8abed8b5af35cb879abbb0e2ba4de21b5f097c08/enable-rdp.ps1''))'
clone_script:
- cmd: git clone -q --depth=1 https://github.com/Croteam-official/Serious-Engine.git %APPVEYOR_BUILD_FOLDER%
environment:
  RDP_PASSWORD:
    secure: EPntnepDJxCOkdpUUnJiYQ==
build:
  verbosity: minimal