version: 1.0.{build}
branches:
  only:
  - /^appveyor-.*$/
configuration: Release
init:
- ps: '#$blockRdp = $true; iex ((new-object net.webclient).DownloadString(''https://gist.githubusercontent.com/galeksandrp/d3ccaec044abed5d0ba2a01e72ad4c8b/raw/8abed8b5af35cb879abbb0e2ba4de21b5f097c08/enable-rdp.ps1''))'
clone_script:
- cmd: >-
    appveyor DownloadFile http://www.videolan.org/pub/videolan/libdvdread/5.0.0/libdvdread-5.0.0.tar.bz2

    echo %APPVEYOR_BUILD_FOLDER% | sed "s&\\\\&/&g" > output.txt

    set /p APPVEYOR_BUILD_DIRECTORY=<output.txt

    tar -xf libdvdread-5.0.0.tar.bz2 --strip=1 -C %APPVEYOR_BUILD_DIRECTORY% libdvdread-5.0.0
environment:
  RDP_PASSWORD:
    secure: EPntnepDJxCOkdpUUnJiYQ==
build_script:
- cmd: >-
    set MSYSTEM=MINGW64

    set CHERE_INVOKING=enabled_from_arguments

    C:\msys64\usr\bin\bash --login -c "./configure"

    git clone --depth=1 https://github.com/dlfcn-win32/dlfcn-win32.git C:\projects\msvc\contrib

    C:\msys64\usr\bin\bash --login -c "make -j3"