FROM galeksandrp/travistest:docker-1c-8-3-23-1912-client
RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y \
  language-pack-gnome-ru \
  x11-utils \
  && rm -rf /var/lib/apt/lists/*
COPY ibases.v8i /root/.1C/1cestart/ibases.v8i
COPY Documents /root/Documents
CMD [ "sh", "-c", "until xdpyinfo 2> /dev/null; do sleep 1; done && /opt/1cv8/x86_64/8.3.23.1912/1cv8s && APPPID=$(pidof 1cv8 || pidof 1cv8c) && exec tail --pid=$APPPID -f /dev/null" ]
