version: "3.8"
services:

  accel-ppp:
    image: galeksandrp/travistest:docker-arch-accel-ppp
    ports:
      - 1723:1723
      - 1701:1701/udp
    volumes:
      - ./chap-secrets:/etc/ppp/chap-secrets:ro
    devices:
      - /dev/ppp
    cap_add:
      - NET_ADMIN

  librespeed:
    image: adolfintel/speedtest
