FROM galeksandrp/travistest:docker-1c-server-8-3-20-1674
COPY --chown=usr1cv8:grp1cv8 1cv8 /home/usr1cv8/.1cv8/1C/1cv8
CMD [ "sh", "-c", "chown -R usr1cv8:grp1cv8 /home/usr1cv8/.1cv8/1C/1cv8 && /opt/1cv8/x86_64/8.3.20.1674/srv1cv83 start && exec tail --pid=$(pidof ragent) -f /dev/null" ]
