FROM galeksandrp/travistest:docker-1c-8-3-23-1912-server
COPY --chown=usr1cv8:grp1cv8 1cv8 /home/usr1cv8/.1cv8/1C/1cv8
CMD [ "/opt/1cv8/x86_64/8.3.23.1912/ragent", "-d", "/home/usr1cv8/.1cv8/1C/1cv8", "-port", "1540", "-regport", "1541", "-range", "1560:1591", "-seclev", "0", "-pingPeriod", "1000", "-pingTimeout", "5000" ]
