FROM alpine:3.16.2
RUN apk add --no-cache xorg-server \
    xf86-video-dummy \
    xrandr
RUN wget -O /usr/share/X11/xorg.conf.d/20-xdummy.conf https://raw.githubusercontent.com/Xpra-org/xpra/master/fs/etc/xpra/xorg.conf
RUN echo '#!/usr/bin/env sh' > /root/.xinitrc
RUN echo 'xrandr --output DUMMY0 --mode 1920x1080' >> /root/.xinitrc
RUN echo 'sleep infinity' >> /root/.xinitrc
RUN chmod +x /root/.xinitrc
CMD ["xinit"]
