version: "3.8"
services:

  accel-ppp:
    image: galeksandrp/travistest:docker-arch-accel-ppp-git-forward
    volumes:
      - ./chap-secrets:/etc/ppp/chap-secrets:ro
    devices:
      - /dev/ppp
    cap_add:
      - NET_ADMIN
    network_mode: host

  librespeed:
    image: adolfintel/speedtest
