FROM alpine:3.16.2 AS base
RUN apk add --no-cache xrdp
RUN apk add --no-cache xorg-server
RUN apk add --no-cache xorgxrdp
RUN apk add --no-cache xterm
RUN sed -i 's/^param=-nolisten$/param=-ac\nparam=-listen/' /etc/xrdp/sesman.ini
# requires docker run --init or compose init: true
CMD ["xrdp-sesman && exec xrdp --nodaemon"]
