version: "3.8"
services:

  xl2tpd:
    image: galeksandrp/travistest:docker-arch-xl2tpd-forward
    volumes:
      - ./chap-secrets:/etc/ppp/chap-secrets:ro
      - ./chap-secrets:/etc/ppp/pap-secrets:ro
    devices:
      - /dev/ppp
    cap_add:
      - NET_ADMIN
    network_mode: host

  librespeed:
    image: adolfintel/speedtest
