#!/usr/bin/env bash
. /etc/ppp/ip-common-accel.sh

echo "$PPP_INTERFACE ip-down"

iptables -t mangle -D FORWARD -i $PPP_INTERFACE -j MARK --set-mark 7368816

# See /etc/ppp/ip-pre-up script
iptables -t filter -D FORWARD -i $PPP_INTERFACE -j ACCEPT
iptables -t filter -D FORWARD -o $PPP_INTERFACE -j ACCEPT

# See /etc/ppp/ip-up script
if isRouter; then
	ip route delete 10.0.0.0/8 dev $PPP_INTERFACE
fi
