#!/usr/bin/env bash
. /etc/ppp/ip-common-accel.sh

echo "$PPP_INTERFACE ip-pre-up"

iptables -t mangle -A FORWARD -i $PPP_INTERFACE -j MARK --set-mark 7368816

# To enable traffic to machines behind PPP caller, you need to do something like that on PPP caller (xl2tpd-1.3.7 example)
# echo -e '#!/usr/bin/env bash\niptables -t filter -A FORWARD -i $PPP_IFACE -j ACCEPT' > /etc/ppp/ip-up.d/iptables-filter-forward-ppp-iface-accept
# echo -e '#!/usr/bin/env bash\niptables -t filter -D FORWARD -i $PPP_IFACE -j ACCEPT' > /etc/ppp/ip-down.d/iptables-filter-forward-ppp-iface-accept
# chmod +x /etc/ppp/ip-up.d/iptables-filter-forward-ppp-iface-accept
# chmod +x /etc/ppp/ip-down.d/iptables-filter-forward-ppp-iface-accept
iptables -t filter -A FORWARD -i $PPP_INTERFACE -j ACCEPT
# Some setups does not allow traffic to PPP tunnel by default
iptables -t filter -A FORWARD -o $PPP_INTERFACE -j ACCEPT

# To enable traffic to MiniUPnPD forwarded ports
# echo -e '#!/usr/bin/env bash\niptables -t nat -A PREROUTING -i $PPP_IFACE -j MINIUPNPD\niptables -t nat -A POSTROUTING -o $PPP_IFACE -j MINIUPNPD-POSTROUTING' > /etc/ppp/ip-up.d/iptables-nat-miniupnpd
# echo -e '#!/usr/bin/env bash\niptables -t nat -D PREROUTING -i $PPP_IFACE -j MINIUPNPD\niptables -t nat -D POSTROUTING -o $PPP_IFACE -j MINIUPNPD-POSTROUTING' > /etc/ppp/ip-down.d/iptables-nat-miniupnpd
# chmod +x /etc/ppp/ip-up.d/iptables-nat-miniupnpd
# chmod +x /etc/ppp/ip-down.d/iptables-nat-miniupnpd
if isRouter; then
    iptables -t nat -A PREROUTING -i $PPP_DEFAULT_INTERFACE -p tcp -d $PPP_DEFAULT_INTERFACE_IP --dport 22 -j RETURN
    iptables -t nat -A PREROUTING -i $PPP_DEFAULT_INTERFACE -p udp -d $PPP_DEFAULT_INTERFACE_IP --dport 22 -j RETURN
    iptables -t nat -A PREROUTING -i $PPP_DEFAULT_INTERFACE -d $PPP_DEFAULT_INTERFACE_IP -j DNAT --to-destination $PPP_CALLER_IP
fi

# To enable port forwarding to tunnel on Wive-RTNL
# echo -e '#!/usr/bin/env bash\n/etc/portforward_vpn A $PPP_IFACE $PPP_LOCAL' > /etc/ppp/ip-up.d/iptables-nat-portforward
# echo -e '#!/usr/bin/env bash\n/etc/portforward_vpn D $PPP_IFACE $PPP_LOCAL' > /etc/ppp/ip-down.d/iptables-nat-portforward
# chmod +x /etc/ppp/ip-up.d/iptables-nat-portforward
# chmod +x /etc/ppp/ip-down.d/iptables-nat-portforward
