#!/usr/bin/env bash
. /etc/ppp/ip-common-accel.sh

echo "$PPP_INTERFACE ip-pre-up"

iptables -t mangle -A FORWARD -i $PPP_INTERFACE -j MARK --set-mark 7368816

# To enable traffic from machines behind PPP caller, you need
# to do that on PPP caller as well
iptables -t filter -A FORWARD -i $PPP_INTERFACE -j ACCEPT
iptables -t filter -A FORWARD -o $PPP_INTERFACE -j ACCEPT
