version: 2
jobs:
  build:
    docker:
      - image: galeksandrp/travistest:docker-build-android-openjdk8
    steps:
      - checkout
      - run: echo $PUBLIC_KEY2 >> ~/.ssh/authorized_keys || true
      - run: echo $PUBLIC_KEY2 | sudo tee /root/.ssh/authorized_keys || true
      - run: TERM=xterm watch -n 540 echo 'LOL'
workflows:
  version: 2
  build_and_test:
    jobs:
      - build:
          filters:
            branches:
              only: /circle-.*/
