version: 2
jobs:
  build:
    machine: true
    environment:
      FILES: "IE8.Win7.VirtualBox.zip\nIE9.Win7.VirtualBox.zip\nIE10.Win7.VirtualBox.zip\nIE11.Win7.VirtualBox.zip"
    steps:
      - checkout
      - run: echo "export BRANCH=$(echo $CIRCLE_BRANCH | sed 's/^circle-//')" >> $BASH_ENV
      - run: curl https://developer.microsoft.com/en-us/microsoft-edge/api/tools/vms/ > /tmp/vms.json
      - run: echo "export VERSION=$(echo -e "$FILES" | xargs -i bash -c 'cat /tmp/vms.json | jq -r ".[].software[].files[]|select(.name==\"{}\").url"' | grep -o -P '[0-9]{8}' | sort | uniq | tail -1)" >> $BASH_ENV
      - run: sudo apt-get update && sudo apt-get install -y linux-headers-$(uname -r) virtualbox
      - run: wget https://releases.hashicorp.com/packer/1.2.4/packer_1.2.4_linux_amd64.zip
      - run: unzip packer_1.2.4_linux_amd64.zip -d ~/bin
      - run: chmod +x ~/bin/packer
      - run: echo -e "$FILES" | xargs -P 4 -L 1 -i bash -c 'wget $(cat /tmp/vms.json | jq -r ".[].software[].files[]|select(.name==\"{}\").url") && unzip {} && rm {}'
      - run: packer build $BRANCH.json
