 version: 2
 jobs:
   build:
     docker:
       - image: galeksandrp/travistest:docker-build-android-alps
     steps:
       - checkout
       - run: apt-get update && apt-get install -y wget
#
# Common environment variables
       - run: echo 'export PREFIX=https://github.com/galeksandrp/travistest/releases/download/deploy-alps3' >> $BASH_ENV
       - run: echo 'export CUSTOMER=HCT6580_WE_N' >> $BASH_ENV
       - run: echo "export CUSTOMER_PROJECT=ALPS-MP-N0.MP2-V1_$CUSTOMER" >> $BASH_ENV
#
# ALPS source download & verify & checkout
       - run: wget "$PREFIX/$CUSTOMER_PROJECT.md5"
       - run: cat "$CUSTOMER_PROJECT.md5" | sed "s^.\+  ^$PREFIX/^" | wget -i -
       - run: md5sum -c ${customer_project}.md5
       - run: tar zxf ${customer_project}_KERNEL.tar.gz
       - run: cat ${customer_project}_INHOUSE.tar.gz* | tar zxf -
#
# ALPS modem download & checkout 
       - run:
           command: echo 'export BRANCH_LABEL_NAME=MOLY.WR8.W1449.MD.WG.MP.V91.5' >> $BASH_ENV
       - run:
           command: wget "$PREFIX/${CUSTOMER}_GPRS_HSPA_$BRANCH_LABEL_NAME.tar.gz"
           working_directory: ~/alps-modem
       - run:
           command: tar zxf "${CUSTOMER}_GPRS_HSPA_$BRANCH_LABEL_NAME.tar.gz" --no-same-owner
           working_directory: ~/alps-modem
       - run:
           command: ./make.sh "${CUSTOMER}_HSPA.mak" new
           working_directory: ~/alps-modem
