version: 2
jobs:
  build:
    docker:
      - image: galeksandrp/travistest:docker-offlineimap
    steps:
      - checkout
      - run: echo -e "machine galeksandrp.visualstudio.com\nlogin $VSTS_NAME\npassword $VSTS_TOKEN" >> ~/.netrc
      - run: git remote add gitlab https://galeksandrp.visualstudio.com/_git/2833
      - run: git fetch gitlab $BRANCH
      - run: git worktree add -b $BRANCH ~/mail gitlab/$BRANCH
      - run: sed -i -e "s/OFFLINEIMAP_EMAIL/$EMAIL/" -e "s/OFFLINEIMAP_PASSWORD/$EMAIL_PASSWORD/" ./.offlineimaprc
      - run: git fetch gitlab offlineimap
      - run: git worktree add -b offlineimap ~/logs gitlab/offlineimap
      - run: remote_syslog -p 15551 -d logs2.papertrailapp.com --pid-file=/var/run/remote_syslog.pid ~/logs/$EMAIL.log
      - run: |
          TERM=xterm watch -n 540 echo 'LOL' &
          offlineimap -c ./.offlineimaprc &> ~/logs/$EMAIL.log
      - run:
          command: git add $EMAIL.log
          working_directory: ~/logs
      - run:
          command: git commit -m 'Upd'
          working_directory: ~/logs
      - run:
          command: git push gitlab offlineimap
          working_directory: ~/logs
      - run:
          command: git add .
          working_directory: ~/mail
      - run:
          command: git commit -m 'Upd' > /dev/null
          working_directory: ~/mail
      - run:
          command: git push gitlab $BRANCH
          working_directory: ~/mail
