on:
  schedule:
    - cron: '0 20 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - run: |
          curl -X POST 'https://ci.appveyor.com/api/builds' -H 'Authorization: Bearer ${{ env.APPVEYOR_TOKEN }}' -H 'Content-Type: application/json' -d '{"accountName": "galeksandrp", "projectSlug": "au-packages", "branch": "1c"}'
      - run: |
          curl -X POST 'https://ci.appveyor.com/api/builds' -H 'Authorization: Bearer ${{ env.APPVEYOR_TOKEN }}' -H 'Content-Type: application/json' -d '{"accountName": "galeksandrp", "projectSlug": "au-packages", "branch": "master"}'
