name: Docker

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:
  schedule:
    - cron: '0 23 * * *'
  push:
    branches:
      - '**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - run: git fetch --no-tags --unshallow origin

      - run: git branch -r --list 'origin/docker-*' | cut -d/ -f2 | xargs -i docker pull ${{ github.repository }}:{}
