on:
  schedule:
    - cron: '0 23 * * *'
  workflow_dispatch:
    inputs:
      tags:
        description: 'Test'
        required: false 
        type: boolean

jobs:
  docker-pull:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: git unshallow
        run: git fetch --no-tags --unshallow origin

      - name: docker pull
        run: git branch -r --list 'origin/docker-*' | cut -d/ -f2 | xargs -i bash -c 'docker pull ${{ github.repository }}:{} > /dev/null && echo fetched {} || echo failed to fetch {} ; docker rmi ${{ github.repository }}:{} > /dev/null && echo removed {} || echo failed to remove {}'
