on:
  schedule:
    - cron: '0 18 * * *'
  workflow_dispatch:
    inputs:
      tags:
        description: 'Test'
        required: false 
        type: boolean

jobs:
  git-branches:
    runs-on: ubuntu-latest
    outputs:
      job: ${{ steps.git-branches.outputs.step }}

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - id: git-branches
        run: echo "::set-output name=step::$(git branch -r --list 'origin/*-ltsc2022*' | cut -d '/' -f2 | jq  --raw-input | jq --slurp -c)"

  docker-build:
    needs: git-branches
    runs-on: windows-2022
    continue-on-error: true
    strategy:
      matrix:
        branch: ${{ fromJson(needs.git-branches.outputs.job) }}

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ matrix.branch }}

      - run: echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ github.actor }} --password-stdin

      - run: docker build --pull -t ${{ github.repository }}:${{ matrix.branch }} .
      - run: docker push ${{ github.repository }}:${{ matrix.branch }}
