on:
  schedule:
    - cron: '0 19 * * 1'
  workflow_dispatch:
    inputs:
      tags:
        description: 'Test'
        required: false 
        type: boolean

jobs:
  docker-build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
        - GITHUB_REPO: Jackett
          GITHUB_UPSTREAM: Jackett
          GITHUB_BRANCH: no-filters-ci
          GITHUB_UPSTREAM_BRANCH: master
        - GITHUB_REPO: AdAway
          GITHUB_UPSTREAM: AdAway
          GITHUB_BRANCH: ci
          GITHUB_UPSTREAM_BRANCH: master
        - GITHUB_REPO: XPrivacyLua
          GITHUB_UPSTREAM: M66B
          GITHUB_BRANCH: ci
          GITHUB_UPSTREAM_BRANCH: master
        - GITHUB_REPO: lawnchair
          GITHUB_UPSTREAM: LawnchairLauncher
          GITHUB_BRANCH: stable
          GITHUB_UPSTREAM_BRANCH: 9-stable

    steps:
      - run: git config --global user.email "3586205+galeksandrp@users.noreply.github.com"
      - run: git config --global user.name "Github CI"

      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          repository: ${{ github.repository_owner }}/${{ matrix.GITHUB_REPO }}
          ref: ${{ matrix.GITHUB_BRANCH }}
          fetch-depth: 0
          token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}

      - run: git remote add upstream https://github.com/${{ matrix.GITHUB_UPSTREAM }}/${{ matrix.GITHUB_REPO }}.git
      - run: git fetch upstream
      - run: git rebase upstream/${{ matrix.GITHUB_UPSTREAM_BRANCH }}
      - run: git push -f origin ${{ matrix.GITHUB_BRANCH }}
