on:
  schedule:
    - cron: '0 17 * * *'
  workflow_dispatch:
    inputs:
      tags:
        description: 'Test'
        required: false 
        type: boolean

jobs:
  docker-pull:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - run: docker run --rm -v${PWD}/bin:/root/openwrt-imagebuilder-25.12.4-x86-64.Linux-x86_64/bin galeksandrp/travistest:docker-openwrt-imagebuilder

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: vlatest
          files: bin/targets/x86/64/*
